### ISSUE TITLE
Getting no /dev/tty from gpg when building Docker

### ISSUE THREAD

**Issue by jeremyheslop** [dougvk/lightning-node#16]
Needed to add --no-tty to gpg commands in Dockerfile for it to build in Centos 7

    && gpg --no-tty --import ./laanwj-releases.asc \
    && gpg --no-tty --verify SHA256SUMS.asc \

A pretty simple change that should work across the board. If you need more testing I can submit a pull request but figured it was small enough to just post here for others.

**Comment by dougvk** [comment]
please submit pull -- thanks!

**Comment by jeremyheslop** [comment]
Closed via commit #17
