### ISSUE TITLE
What happens if i kill the Lightning Node docker ?

### ISSUE THREAD

**Issue by brunoaduarte** [dougvk/lightning-node#2]
Hi!

I followed your tutorial, but instead of DigitalOcean, i did it all on a Linux VM on my computer, and now i have the bitcoin and lightning docker running. I also have an opened channel with funds i've just added.
If i kill the docker instance or restart the VM, will i lose access to this channel + funds ? Or is it possible to reconnect to the channel later ? I'm afraid of restarting my computer and losing access to my funds.

Thanks !

**Comment by deksprime** [comment]
Hello. I have also followed the tutorial and now running the node and LN node but have the same problem. I can't turn off my PC with the fear of losing my funds(not that it's too much but still :)) now what is the way to properly handle this situation?

**Comment by caner** [comment]
Don't worry folks. Lightning container saves all the data Docker hosts' "data" volume (In this tutorial, "/scratch/bitcoin/mainnet/clightning"). So, unless you delete your Docker host, all your funds will keep on being safe.

**Comment by brunoaduarte** [comment]
I wasn't sure, cause the first time i stopped the lightning daemon it totally killed the container. So i closed my channel, and now i'm waiting for the 144th confirmation block to get my funds back.
Thanks anyway @caner

**Comment by erkanefe** [comment]
@caner hocam sync esnasında uzun süre bekleme olabiliyor mu? kurulumu digitalocean üzerinde yapıyorum. sync başladıktan sonra son aldığım logda 560mb indirilmiş görünüyor. Sonra bandwith 0'a düştü. Son yarım saatir indirmiyor.
